name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run build
        run: make
      - name: run lint
        run: cargo fmt -- --check
      - name: run tests
        run: cargo test
      - name: run the application as a smoke test
        run: ./target/release/dank
