name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run build
        run: make
      - name: run lint
        run: cargo fmt -- --check
      - name: run tests
        run: cargo test
      - name: run the application as a smoke test
        run: ./target/release/dank
      - name: upload build
        uses: actions/upload-artifact@v2
        with:
          name: dank_${{ matrix.platform.target }}
          path: target/release/dank
