name: Continous Deployment

on:
  push:
    tags:
      - "v.*.*.*"

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux
          - os: macos-latest
            target: x86_64-apple-darwin
            platform: macos
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Package
        run: |
          cd target/${{ matrix.target }}/release

          RELEASE_NAME=dank-${{ matrix.platform }}
          RELEASE_TAR=$RELEASE_NAME.tar.gz
          RELEASE_TAR_SUM=$RELEASE_NAME.sha256

          tar czcf $RELEASE_TAR dank
          shasum -a 256 $RELEASE_TAR > $RELEASE_TAR_SUM
      - name: Publish assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/spotify-tui-${{ matrix.platform }}.tar.gz
            target/${{ matrix.target }}/release/spotify-tui-${{ matrix.platform }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
