name: Continous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux
          - os: macos-latest
            target: x86_64-apple-darwin
            platform: macos
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the tag name
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Build
        run: cargo build --release --target ${{ matrix.platform.target }}
      - name: Package
        run: |
          cd target/${{ matrix.platform.target }}/release

          tar czvf dank-${{ env.VERSION }}-${{ matrix.platform.platform }}.tar.gz dank
          shasum -a 256 dank-${{ env.VERSION }}-${{ matrix.platform.platform }}.tar.gz > dank-${{ env.VERSION }}-${{ matrix.platform.platform }}.sha256
      - name: Publish assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.platform.target }}/release/dank-${{ env.VERSION }}-${{ matrix.platform.platform }}.tar.gz
            target/${{ matrix.platform.target }}/release/dank-${{ env.VERSION }}-${{ matrix.platform.platform }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
